version: '3.8'

services:
  xsshunterexpress-db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-db-data:/var/lib/postgresql/data/pgdata

  xsshunterexpress-service:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./payload-fire-images:/app/payload-fire-images
      # If you need Google Cloud credentials, consider using secrets or a mounted file within the project directory
      # - ./gcloud-credentials.json:/gcloud.json
    depends_on:
      xsshunterexpress-db:
        condition: service_healthy

  xsshunterexpress-trufflehog:
    build:
      dockerfile: Dockerfile.trufflehog
    restart: unless-stopped
    ports:
      - 8000:8000

  xsshunterexpress-proxy:
    image: caddy:alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
